apiVersion: v1
kind: Namespace
metadata:
  name: hopps-dev
  labels:
    # postgres-cluster can't be configured to be pss "restricted" profile
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.31
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.31
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.31
