apiVersion: v1
kind: Service
metadata:
  name: {{ include "hopps.hoppsAppFullname" . }}
  labels:
    {{- include "hopps.hoppsAppLabels" . | nindent 4 }}
spec:
  type: {{ .Values.hoppsApp.service.type }}
  ports:
    - port: {{ .Values.hoppsApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "hopps.hoppsAppSelectorLabels" . | nindent 4 }}
