{{- if .Values.hoppsApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.hoppsApp.serviceAccount.name | default (include "hopps.hoppsAppFullname" .) }}
  labels:
    {{- include "hopps.hoppsAppLabels" . | nindent 4 }}
  {{- with .Values.hoppsApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.hoppsApp.serviceAccount.automount }}
{{- end }}
