apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hopps
spec:
  chart:
    spec:
      chart: hopps
      sourceRef:
        kind: HelmRepository
        name: hopps
      version: 2.0.0
  interval: 1m0s
  values:
    # az-document-ai
    azDocumentAi:
      image:
        tag: "657"
      envFrom:
        - secretRef:
            name: az-document-ai
    # hopps-app (merged org + frontend)
    hoppsApp:
      image:
        repository: ghcr.io/hopps-app/hopps/hopps-app
        tag: "657"
      envFrom:
        - secretRef:
            name: hopps-app
      envVars:
        # Database secrets
        - name: quarkus.datasource.jdbc.url
          value: jdbc:postgresql://postgres-cluster-rw:5432/hopps-app?loggerLevel=OFF&sslmode=require
        - name: quarkus.swagger-ui.always-include
          value: "true"
        - name: quarkus.swagger-ui.enable
          value: "true"
        - name: quarkus.swagger-ui.path
          value: /q/swagger-ui
        - name: quarkus.smallrye-openapi.path
          value: /q/openapi
        - name: quarkus.datasource.username
          valueFrom:
            secretKeyRef:
              name: hopps-app-db-secret
              key: username
        - name: quarkus.datasource.password
          valueFrom:
            secretKeyRef:
              name: hopps-app-db-secret
              key: password
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.${DOMAIN_2}, http://localhost:5173"
        ingressClassName: nginx
        hosts:
          - host: dev.${DOMAIN_2}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: hopps-app-tls
            hosts:
              - dev.${DOMAIN_2}
      managementIngress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/server-snippet: |
            location = /swagger {
              return 302 /q/swagger-ui;
            }
        hosts:
          - host: api.dev.${DOMAIN_2}
            paths:
              - path: /q/swagger-ui
                pathType: Prefix
              - path: /q/openapi
                pathType: Prefix
        tls:
          - secretName: api-tls
            hosts:
              - api.dev.${DOMAIN_2}
    # disable subchart for postgresql
    postgresqlHoppsApp:
      enabled: false
    zugferd:
      image:
        tag: "657"
    # use already available keycloak
    keycloak:
      http:
        # For backwards compatibility reasons we set this to the value used by previous Keycloak versions.
        relativePath: "/"
      tag: 32-keycloak-26.2.1
      enabled: true
      database:
        vendor: postgres
        hostname: postgres-cluster-rw
        port: 5432
        database: keycloak
        username: keycloak
        existingSecret: keycloak-db-secret
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.${DOMAIN_2}, https://demo.${DOMAIN_2}, http://localhost:5173"
          # disable public access to metrics endpoint
          nginx.ingress.kubernetes.io/server-snippet: |
            location ~* /auth/realms/[^/]+/metrics {
                return 403;
            }
        rules:
          - host: id.dev.${DOMAIN_2}
            paths:
              - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
                pathType: Prefix
        tls:
          - secretName: keycloak-tls
            hosts:
              - id.dev.${DOMAIN_2}
        ingressClassName: nginx
      serviceMonitor:
        enabled: true
