name: Build az-document-ai-service

on:
  push:
    branches: [ main, deploy ]
    paths:
      - 'app.fuggs.az-document-ai/**'
      - '.github/workflows/az-document-ai-service.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: app.fuggs.az-document-ai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B verify

      - name: Cache SonarQube packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube analysis
        if: ${{ !startsWith(github.ref, 'refs/heads/dependabot') }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw -B sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=fuggs-app \
            -Dsonar.projectKey=fuggs-app_fuggs-document-ai

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v6
        with:
          context: app.fuggs.az-document-ai
          push: true
          file: app.fuggs.az-document-ai/src/main/docker/Dockerfile.jvm
          tags: |
            ghcr.io/fuggs-app/az-document-ai-service:latest
            ghcr.io/fuggs-app/az-document-ai-service:${{ github.run_number }}

      - name: Trigger deploy workflow
        uses: actions/github-script@v8
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github-token: ${{ secrets.TECHNICAL_USER_PAT }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'fuggs-app',
              repo: 'fuggs.cloud',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                "environment": "dev",
                "new-tag": "${{ github.run_number }}",
                "service-name": "azDocumentAi"
              }
            })
            console.log(result);
